import { Inter } from 'next/font/google'
// all pages will inherit global css classes
//merge test update
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* create leayout for pages, where you will add commonly used components such as navbar, header, footer, etc. */}
      <body className={inter.className}>{children}</body>
    </html>
  )
}
